#!/bin/bash

####################
#
# Quick script to setup 
# working env, jerks
#
#####################

# First things first, we need to do some cleanup

if [[ -f ~/.bashrc ]] ; then
  rm ~/.bashrc
fi

if [[ -f ~/.bash_profile ]] ; then
  rm ~/.bash_profile
fi

if [[ -f ~/.vimrc ]] ; then
  rm ~/.vimrc
fi

if [[ -f ~/.tmux.conf ]] ; then
  rm ~/.tmux.conf
fi

if [[ -d ~/.vim ]] ; then
  mkdir ~/.vim/bundle ~/.vim/autoload
else
  mkdir -p ~/.vim/bundle ~/.vim/autoload
fi

if [[ -f ~/.irssi/config ]]; then
  rm ~/.irssi/config
else
  mkdir ~/.irssi
fi
  

# install VIM Pathogen

curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Now to make some symlinks

ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.bashrc ~/.bash_profile
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.irssi/config ~/.irssi/config

# Get freenode password from arg

if [[ -n "$1" ]] ; then
  sed -i -e 's/[A-Za-z0-9]*FREENODEPASSWORD[A-Za-z0-9]*/'$1'/' ~/.irssi/config
fi
